import "@/app/globals.css";
import type { Metadata } from "next";
import Image from "next/image";
import { withBasePath } from "@/lib/basePath";
// import Sidebar from "./components/shared/SideBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main>
      <div className="flex relative w-screen h-screen">
        {/* <Sidebar /> */}
        <div className="flex flex-col w-[calc(100%-48px)] max-w-s max-h-screen mx-6 mt-8 md:mx-8 md:mt-12 lg:mx-12 lg:mt-16 xl:mx-20 xl:mt-20">
          {/* <div className="flex flex-col w-full max-h-screen ml-12 mt-20"> */}
          <Image
            className="z-50 mx-auto lg:mx-0"
            src={withBasePath("/img/Logo_Deepia_Horizontal_white.svg")}
            alt="Hero"
            height={104}
            width={323}
            priority
          />
          {/* <p className="text-white bg-red-500 z-50">asdasd</p> */}

          {/* <div className="flex w-[calc(100%-48px)] max-w-screen max-h-screen h-full absolute top-0 left-0 pt-20"> */}
          {/* <div className="flex w-full mx-6 mt-8 md:mx-8 md:mt-12 lg:mx-12 lg:mt-16 xl:mx-20 xl:mt-20"> */}
          {children}
          {/* </div> */}
          {/* </div> */}
        </div>
      </div>
    </main>
  );
}
