import "@/app/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Sidebar from "./components/shared/SideBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>
          <div className="flex bg-gray-800">
            <Sidebar />
            <div className="flex flex-col w-full h-screen">{children}</div>
          </div>
        </main>
      </body>
    </html>
  );
}
