import "@/app/globals.css";
import type { Metadata } from "next";
// import Sidebar from "./components/shared/SideBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main>
      <div className="flex">
        {/* <Sidebar /> */}
        <div className="flex flex-col w-full h-screen">{children}</div>
      </div>
    </main>
  );
}
